### ISSUE TITLE
[Suggestion] Dependabot

### ISSUE THREAD

**Issue by kevinmatthes** [AmmarAbouZor/tui-journal#49]
Dependabot is a technology shipped with and maintained by GitHub to automatically suggest version updates for the configured dependencies.  This is very useful in order to keep the project up-to-date and secure as the updates might also contain security fixes.  This project uses Rust crates and GitHub Actions, so the following setup would be useful for an initial configuration:

```yaml
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: '00:00'
    assignees:
      - AmmarAbouZor
    commit-message:
      prefix: 'Chore: '

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '00:00'
    assignees:
      - AmmarAbouZor
    commit-message:
      prefix: 'Chore: '
```

Every day at UTC midnight (after a delay of usually about 1.75 hours), Dependabot will search for updates for your configured dependencies and suggest them as PRs.  You will be set as assignee and both the commit and the PR will be named similarly with the prefix `Chore: `, followed by the actual update, e.g. `Chore:  bump clap from 4.3.0 to 4.3.3`.  The prefix "chore" is usual for Dependabot version updates, Clap, for example, uses it, as well.  Furthermore, that prefix is also configured as skip condition for the CHANGELOG fragment generation.

Unfortunately, the check interval cannot be set to hourly but you are allowed to invoke the Depedabot check for updates manually from the Insights tab of this repository (Insights → Dependency graph → Dependabot → Last checked ... → Check for updates).  If the daily interval should be too much, you can also set it to once a week or once a month.

There is also another bot to check for updates:  Renovate.  This bot is used by Clap and is able to do basically the same, i.e. checking for version updates of dependencies.  However, I only used Dependabot, so far, so I cannot assist you in configuring Renovate.  Furthermore, it would cause trouble if I would suggest you the above configuration in a PR, so the easiest way to enable Dependabot is to copy the configuration and to paste it to a file named `.github/dependabot.yml`.  If you wish to disable Dependabot in the future, just delete its configuration file; then, you can use another tool like Renovate, for example.
